version: '3'
services:
  web:
    image: zhangyahan/electron-release-server
    environment:
      APP_USERNAME: admin
      APP_PASSWORD: admin@1234.
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: releaseserver
      DB_USERNAME: releaseserver
      DB_PASSWORD: releaseserver
      TOKEN_SECRET: change_me_in_production
      APP_URL: '192.168.30.26:5000'
      ASSETS_PATH: '/usr/src/electron-release-server/releases'
    depends_on:
      - db
    ports:
      - '5000:80'
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: releaseserver
      POSTGRES_USER: releaseserver
    volumes:
      - ./postgres:/var/lib/postgresql/data

